---
- name: Using tasks
  hosts: 127.0.0.1
  connection: local
#  become: yes
 
  environment:
     PYTHONPATH: "{{ lookup('env', 'PWD') }}/django/django/notejam"
  
  roles:
  - mysql_db
  - django-web

